// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdkcbmvjwsocrfnjrtku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ka2NibXZqd3NvY3JmbmpydGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzAxNzAsImV4cCI6MjA1ODkwNjE3MH0.fD-Vnw3ykGoi1xh9Q82kPB448eajP9qlcTZbqriZMlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);